/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import entidades.Amostra;
import entidades.Local;
import entidades.Paciente;
import entidades.Tipo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Banco;

/**
 *
 * @author Bruno Vicente
 */
public class JanelaCadastro extends javax.swing.JDialog {
    private java.awt.Frame parent;
    
    private Paciente paciente = null;
    private Amostra amostra = null;
    
    /**
     * Creates new form JanelaCadastro
     */
    public JanelaCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setLocationRelativeTo(null);
        this.inicializar();
    }
    
    public JanelaCadastro(java.awt.Frame parent, boolean modal, Amostra amostra) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
                this.parent = parent;
                
        this.modoEdicao(amostra);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbutaoSalvar = new javax.swing.JButton();
        jbutaoNovo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobs = new javax.swing.JTextArea();
        jmiel = new javax.swing.JComboBox<>();
        jmedular = new javax.swing.JComboBox<>();
        jmedico = new javax.swing.JTextField();
        jidade = new javax.swing.JTextField();
        jdata = new janelas.JCalendar(false);
        jregistro = new javax.swing.JTextField();
        jpaciente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jdataatual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jbloco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jenfermaria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jleito = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jlocal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabela = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jquantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Amostra");

        jbutaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar.png"))); // NOI18N
        jbutaoSalvar.setText("SALVAR");
        jbutaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoSalvarActionPerformed(evt);
            }
        });

        jbutaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo.png"))); // NOI18N
        jbutaoNovo.setText("NOVO");
        jbutaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoNovoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Paciente"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PACIENTE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("REGISTRO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DATA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("IDADE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("MÉDICO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ASPIRADO MEDULAR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("MIELOCULTURA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("OBSERVAÇÕES");

        jobs.setColumns(20);
        jobs.setRows(5);
        jobs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jobsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jobs);

        jmiel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmiel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Realizou", "Positivo", "Negativo" }));
        jmiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmielActionPerformed(evt);
            }
        });
        jmiel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmielKeyPressed(evt);
            }
        });

        jmedular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmedular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Realizou", "Positivo", "Negativo" }));
        jmedular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmedularKeyPressed(evt);
            }
        });

        jmedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmedicoKeyPressed(evt);
            }
        });

        jidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jidadeKeyPressed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdataKeyPressed(evt);
            }
        });

        jregistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jregistroKeyPressed(evt);
            }
        });

        jpaciente.setEditable(false);
        jpaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpacienteKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jdataatual.setEditable(false);
        jdataatual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("BLOCO");

        jbloco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbloco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jblocoKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ENFERMARIA");

        jenfermaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenfermaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jenfermariaKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("LEITO");

        jleito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jleito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jleitoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jidade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jmedico)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jmedular, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jmiel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbloco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jdataatual, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jenfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jleito, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jdataatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jbloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jenfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jleito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jmedular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jmiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados das Amostras"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TIPO");

        jtipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtipoKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("LOCAL");

        jlocal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlocalKeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtabela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPOL DA AMOSTRA", "LOCAL DA AMOSTRA", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabela.setRowHeight(20);
        jtabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabelaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtabela);
        if (jtabela.getColumnModel().getColumnCount() > 0) {
            jtabela.getColumnModel().getColumn(0).setResizable(false);
            jtabela.getColumnModel().getColumn(1).setResizable(false);
            jtabela.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("QUANTIDADE");

        jquantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jquantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jquantidadeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbutaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutaoSalvar)
                    .addComponent(jbutaoNovo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmielActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.buscarPaciente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpacienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F3){
            this.buscarPaciente();
        }
    }//GEN-LAST:event_jpacienteKeyPressed

    private void jregistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jregistroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jdata.requestFocus();
        }
    }//GEN-LAST:event_jregistroKeyPressed

    private void jdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdataKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbloco.requestFocus();
        }
    }//GEN-LAST:event_jdataKeyPressed

    private void jidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jregistro.requestFocus();
        }
    }//GEN-LAST:event_jidadeKeyPressed

    private void jmedicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmedicoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jmedular.requestFocus();
        }
    }//GEN-LAST:event_jmedicoKeyPressed

    private void jquantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jquantidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.adicionarLocal();
            jtipo.requestFocus();
        }
    }//GEN-LAST:event_jquantidadeKeyPressed

    private void jmedularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmedularKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jmiel.requestFocus();
        }
    }//GEN-LAST:event_jmedularKeyPressed

    private void jmielKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmielKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jobs.requestFocus();
        }
    }//GEN-LAST:event_jmielKeyPressed

    private void jtipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtipoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jlocal.requestFocus();
        }
    }//GEN-LAST:event_jtipoKeyPressed

    private void jobsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
//            if(this.amostra.getId() == 0){
//                this.salvar();
//            }else{
//                this.editar();
//            }
            jtipo.requestFocus();
        }
    }//GEN-LAST:event_jobsKeyPressed

    private void jbutaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoSalvarActionPerformed
        if(this.amostra.getId() == 0){
            this.salvar();
        }else{
            this.editar();
        }
    }//GEN-LAST:event_jbutaoSalvarActionPerformed

    private void jbutaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoNovoActionPerformed
        this.novo();
    }//GEN-LAST:event_jbutaoNovoActionPerformed

    private void jlocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlocalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jquantidade.requestFocus();
        }
    }//GEN-LAST:event_jlocalKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.adicionarLocal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabelaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            this.deleteLocal();
        }
    }//GEN-LAST:event_jtabelaKeyPressed

    private void jblocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jblocoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jenfermaria.requestFocus();
        }
    }//GEN-LAST:event_jblocoKeyPressed

    private void jenfermariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenfermariaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jleito.requestFocus();
        }
    }//GEN-LAST:event_jenfermariaKeyPressed

    private void jleitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jleitoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jmedico.requestFocus();
        }
    }//GEN-LAST:event_jleitoKeyPressed
    
    private void buscarPaciente(){
        this.paciente = new Paciente();
        
        JanelaConsultaPacientes janela = new JanelaConsultaPacientes(parent, true, this.paciente);
        janela.setVisible(true);
        
        if(this.paciente != null){
            jpaciente.setText(this.paciente.getNome());
            jidade.requestFocus();
        }
    }
    
    private void editar(){
        //Amostra amostra = new Amostra();
        amostra.setPaciente(this.paciente);
        amostra.setRegistro(Integer.valueOf(jregistro.getText()));
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");        

        String d = ((JCalendar)jdata).getText();
        
        if(!d.isEmpty()){
            try {
                amostra.setData(new Date(format.parse(d).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(JanelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        amostra.setIdade(Integer.parseInt(jidade.getText()));
        amostra.setMedico(jmedico.getText());
        //amostra.setQuantidade(Integer.parseInt(jquantidade.getText()));
        //amostra.setLocal(jlocal.getText());
        amostra.setBloco(jbloco.getText());
        amostra.setEnfermaria(jenfermaria.getText());
        amostra.setLeito(jleito.getText());
        amostra.setMedular((String) jmedular.getSelectedItem());
        amostra.setMielocultura((String) jmiel.getSelectedItem());
        amostra.setObs(jobs.getText());
        amostra.setUsuario(Banco.getUsuarioLogado());
        
        Banco.getBanco().editar(amostra);
        JOptionPane.showMessageDialog(null, "Amostra modificada com sucesso!");
        this.dispose();        
    }
   
    private void salvar(){
        //Amostra amostra = new Amostra();
        amostra.setPaciente(this.paciente);
        amostra.setRegistro(Integer.valueOf(jregistro.getText()));
        
        //java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 
        String d = ((JCalendar)jdata).getText();
        
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            amostra.setData(new Date(format.parse(d).getTime()));
            amostra.setIdade(Integer.parseInt(jidade.getText()));
            amostra.setMedico(jmedico.getText());
            //amostra.setQuantidade(Integer.parseInt(jquantidade.getText()));
            //amostra.setLocal(jlocal.getText());
            amostra.setMedular((String) jmedular.getSelectedItem());
            amostra.setMielocultura((String) jmiel.getSelectedItem());
            amostra.setObs(jobs.getText());
            amostra.setUsuario(Banco.getUsuarioLogado());
            amostra.setBloco(jbloco.getText());
            amostra.setEnfermaria(jenfermaria.getText());
            amostra.setLeito(jleito.getText());
            
            Banco.getBanco().cadastrar(amostra);
            JOptionPane.showMessageDialog(null, "Amostra cadastrada com sucesso!");
            jbutaoSalvar.setEnabled(false);
            jbutaoNovo.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(JanelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void adicionarLocal(){
        Local local = new Local();
        local.setLocal(jlocal.getText());
        local.setQuantidade(Integer.parseInt(jquantidade.getText()));
        local.setTipo(jtipo.getSelectedItem().toString());
        this.amostra.getLocais().add(local);

        DefaultTableModel modelo = (DefaultTableModel) jtabela.getModel();
        String[] linha = new String[3];
        linha[0] = local.getTipo();
        linha[1] = local.getLocal();
        linha[2] = local.getQuantidade()+"";

        modelo.addRow(linha);
        
        this.jquantidade.setText("");
        this.jlocal.setText("");
        this.jtipo.setSelectedIndex(0);
        
    }//Fim de adicionar Local
    
    private void limparTabela(){
        DefaultTableModel model = (DefaultTableModel) jtabela.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        int tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }

    }
    
    private void novo(){
        
        this.limparTabela();
        
        this.paciente = null;
        
        jpaciente.setText("");
        jregistro.setText("");
        jidade.setText("");
        jmedico.setText("");
        jquantidade.setText("");
        jmedular.setSelectedIndex(0);
        jmiel.setSelectedIndex(0);
        jtipo.setSelectedIndex(0);
        jobs.setText("");
        jbutaoNovo.setEnabled(false);
        jbutaoSalvar.setEnabled(true);
        jpaciente.requestFocus();
        ((DefaultComboBoxModel)jdata.getModel()).removeAllElements();
        
        this.amostra = new Amostra();
        
    }
    
    private void inicializar(){
        jpaciente.requestFocus();
        
        List<Tipo> lista = Banco.getBanco().getTipos();
        jtipo.addItem("");
        for (Tipo tipo : lista) {
            jtipo.addItem(tipo.getNome());
        }
        jdataatual.setVisible(false);
        jbutaoNovo.setEnabled(false);
        this.amostra = new Amostra();
    }
    
    private void modoEdicao(Amostra amostra){
        this.setTitle("Modificar Amostra");

        jpaciente.requestFocus();
        this.amostra = amostra;
        
        List<Tipo> lista = Banco.getBanco().getTipos();
        
        jtipo.addItem("");
        for (Tipo tipo : lista) {
            jtipo.addItem(tipo.getNome());
        }
        
        this.paciente = this.amostra.getPaciente();
        
        jpaciente.setText(this.amostra.getPaciente().getNome());
        jregistro.setText(this.amostra.getRegistro()+"");
        
        java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 
        jdataatual.setText(formatodata.format(this.amostra.getData()));
        
        jbloco.setText(amostra.getBloco());
        jenfermaria.setText(amostra.getEnfermaria());
        jleito.setText(amostra.getLeito());
        
        jidade.setText(this.amostra.getIdade()+"");
        jmedico.setText(this.amostra.getMedico());
        //jquantidade.setText(this.amostra.getQuantidade()+"");
        //jlocal.setText(this.amostra.getLocal());
        
        if(this.amostra.getMedular().equals("Positivo")){
            jmedular.setSelectedIndex(1);
        }else if(this.amostra.getMedular().equals("Negativo")){
            jmedular.setSelectedIndex(2);
        }else{
            jmedular.setSelectedIndex(0);
        }
        
        if(this.amostra.getMielocultura().equals("Positivo")){
            jmedular.setSelectedIndex(1);
        }else if(this.amostra.getMielocultura().equals("Negativo")){
            jmedular.setSelectedIndex(2);
        }else{
            jmedular.setSelectedIndex(0);
        }
        
        jobs.setText(this.amostra.getObs());
        
        //Adicionando Tipos na Tabela
        DefaultTableModel modelo = (DefaultTableModel) jtabela.getModel();
        for (Local local : this.amostra.getLocais()) {
            String[] linha = new String[3];
            linha[0] = local.getTipo();
            linha[1] = local.getLocal();
            linha[2] = local.getQuantidade()+"";

            modelo.addRow(linha);
        }

        this.jquantidade.setText("");
        this.jlocal.setText("");
        this.jtipo.setSelectedIndex(0);
        
        
        jbutaoNovo.setEnabled(false);
    }//Fim Modo Edição
    
    private void deleteLocal(){
        int i = jtabela.getSelectedRow();
        this.amostra.getLocais().remove(i);
        DefaultTableModel modelo = (DefaultTableModel) jtabela.getModel();
        modelo.removeRow(i);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jbloco;
    private javax.swing.JButton jbutaoNovo;
    private javax.swing.JButton jbutaoSalvar;
    private javax.swing.JComboBox<String> jdata;
    private javax.swing.JTextField jdataatual;
    private javax.swing.JTextField jenfermaria;
    private javax.swing.JTextField jidade;
    private javax.swing.JTextField jleito;
    private javax.swing.JTextField jlocal;
    private javax.swing.JTextField jmedico;
    private javax.swing.JComboBox<String> jmedular;
    private javax.swing.JComboBox<String> jmiel;
    private javax.swing.JTextArea jobs;
    private javax.swing.JTextField jpaciente;
    private javax.swing.JTextField jquantidade;
    private javax.swing.JTextField jregistro;
    private javax.swing.JTable jtabela;
    private javax.swing.JComboBox<String> jtipo;
    // End of variables declaration//GEN-END:variables
}
