/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import entidades.Amostra;
import entidades.Local;
import entidades.Paciente;
import entidades.Tipo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Banco;

/**
 *
 * @author Bruno Vicente
 */
public class JanelaVisualiza extends javax.swing.JDialog {
    private java.awt.Frame parent;
    
    private Paciente paciente = null;
    private Amostra amostra = null;
    
    
    public JanelaVisualiza(java.awt.Frame parent, boolean modal, Amostra amostra) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
                this.parent = parent;
                
        this.modoEdicao(amostra);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobs = new javax.swing.JTextArea();
        jmedico = new javax.swing.JTextField();
        jidade = new javax.swing.JTextField();
        jregistro = new javax.swing.JTextField();
        jpaciente = new javax.swing.JTextField();
        jdataatual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jbloco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jenfermaria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jleito = new javax.swing.JTextField();
        jmedular = new javax.swing.JTextField();
        jmiel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VISUALIZAÇÃO DA AMOSTRA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Paciente"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PACIENTE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("REGISTRO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DATA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("IDADE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("MÉDICO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ASPIRADO MEDULAR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("MIELOCULTURA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("OBSERVAÇÕES");

        jobs.setEditable(false);
        jobs.setColumns(20);
        jobs.setRows(5);
        jobs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jobsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jobs);

        jmedico.setEditable(false);
        jmedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmedicoKeyPressed(evt);
            }
        });

        jidade.setEditable(false);
        jidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jidadeKeyPressed(evt);
            }
        });

        jregistro.setEditable(false);
        jregistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jregistroKeyPressed(evt);
            }
        });

        jpaciente.setEditable(false);
        jpaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpacienteKeyPressed(evt);
            }
        });

        jdataatual.setEditable(false);
        jdataatual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("BLOCO");

        jbloco.setEditable(false);
        jbloco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbloco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jblocoKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ENFERMARIA");

        jenfermaria.setEditable(false);
        jenfermaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenfermaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jenfermariaKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("LEITO");

        jleito.setEditable(false);
        jleito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jleito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jleitoKeyPressed(evt);
            }
        });

        jmedular.setEditable(false);
        jmedular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jmiel.setEditable(false);
        jmiel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmiel.setPreferredSize(new java.awt.Dimension(50, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jpaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jidade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jmedico)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jmedular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jmiel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbloco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jenfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jleito, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdataatual, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jdataatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jbloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jenfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jleito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jmedular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados das Amostras"));

        jtabela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPOL DA AMOSTRA", "LOCAL DA AMOSTRA", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabela.setRowHeight(20);
        jtabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabelaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtabela);
        if (jtabela.getColumnModel().getColumnCount() > 0) {
            jtabela.getColumnModel().getColumn(0).setResizable(false);
            jtabela.getColumnModel().getColumn(1).setResizable(false);
            jtabela.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpacienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F3){
            this.buscarPaciente();
        }
    }//GEN-LAST:event_jpacienteKeyPressed

    private void jregistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jregistroKeyPressed
        
    }//GEN-LAST:event_jregistroKeyPressed

    private void jidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jregistro.requestFocus();
        }
    }//GEN-LAST:event_jidadeKeyPressed

    private void jmedicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmedicoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jmedular.requestFocus();
        }
    }//GEN-LAST:event_jmedicoKeyPressed

    private void jobsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobsKeyPressed

    }//GEN-LAST:event_jobsKeyPressed

    private void jblocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jblocoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jenfermaria.requestFocus();
        }
    }//GEN-LAST:event_jblocoKeyPressed

    private void jenfermariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenfermariaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jleito.requestFocus();
        }
    }//GEN-LAST:event_jenfermariaKeyPressed

    private void jleitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jleitoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jmedico.requestFocus();
        }
    }//GEN-LAST:event_jleitoKeyPressed

    private void jtabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabelaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            this.deleteLocal();
        }
    }//GEN-LAST:event_jtabelaKeyPressed
    
    private void buscarPaciente(){
        this.paciente = new Paciente();
        
        JanelaConsultaPacientes janela = new JanelaConsultaPacientes(parent, true, this.paciente);
        janela.setVisible(true);
        
        if(this.paciente != null){
            jpaciente.setText(this.paciente.getNome());
            jidade.requestFocus();
        }
    }
    
    
    
    
        
    private void limparTabela(){
        DefaultTableModel model = (DefaultTableModel) jtabela.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        int tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }

    }
    
    
    
    
    private void modoEdicao(Amostra amostra){
        this.setTitle("Modificar Amostra");

        jpaciente.requestFocus();
        this.amostra = amostra;
        
        List<Tipo> lista = Banco.getBanco().getTipos();
        
       
        this.paciente = this.amostra.getPaciente();
        
        jpaciente.setText(this.amostra.getPaciente().getNome());
        jregistro.setText(this.amostra.getRegistro()+"");
        
        java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 
        jdataatual.setText(formatodata.format(this.amostra.getData()));
        
        jbloco.setText(amostra.getBloco());
        jenfermaria.setText(amostra.getEnfermaria());
        jleito.setText(amostra.getLeito());
        
        jidade.setText(this.amostra.getIdade()+"");
        jmedico.setText(this.amostra.getMedico());
        //jquantidade.setText(this.amostra.getQuantidade()+"");
        //jlocal.setText(this.amostra.getLocal());
        
        jmedular.setText(this.amostra.getMedular());
        
        
        jmiel.setText(this.amostra.getMielocultura());
        
        jobs.setText(this.amostra.getObs());
        
        //Adicionando Tipos na Tabela
        DefaultTableModel modelo = (DefaultTableModel) jtabela.getModel();
        for (Local local : this.amostra.getLocais()) {
            String[] linha = new String[3];
            linha[0] = local.getTipo();
            linha[1] = local.getLocal();
            linha[2] = local.getQuantidade()+"";

            modelo.addRow(linha);
        }

       
    }//Fim Modo Edição
    
    private void deleteLocal(){
        int i = jtabela.getSelectedRow();
        this.amostra.getLocais().remove(i);
        DefaultTableModel modelo = (DefaultTableModel) jtabela.getModel();
        modelo.removeRow(i);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jbloco;
    private javax.swing.JTextField jdataatual;
    private javax.swing.JTextField jenfermaria;
    private javax.swing.JTextField jidade;
    private javax.swing.JTextField jleito;
    private javax.swing.JTextField jmedico;
    private javax.swing.JTextField jmedular;
    private javax.swing.JTextField jmiel;
    private javax.swing.JTextArea jobs;
    private javax.swing.JTextField jpaciente;
    private javax.swing.JTextField jregistro;
    private javax.swing.JTable jtabela;
    // End of variables declaration//GEN-END:variables
}
